"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const order_controller_1 = require("./order.controller");
const jwt_middleware_1 = require("../middlewares/jwt.middleware");
const router = (0, express_1.Router)();
router.use(jwt_middleware_1.jwtMiddleware);
router.get('/', order_controller_1.orderController.getSellerOrders);
router.get('/summary', order_controller_1.orderController.getOrderSummary);
router.get('/status/:status', order_controller_1.orderController.getOrdersByStatus);
router.get('/:id', order_controller_1.orderController.getOrderById);
router.patch('/:id/accept', order_controller_1.orderController.acceptOrder);
router.patch('/:id/reject', order_controller_1.orderController.rejectOrder);
router.patch('/:id/processing', order_controller_1.orderController.processOrder);
router.patch('/:id/deliver', order_controller_1.orderController.deliverOrder);
exports.default = router;
