"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const store_controller_1 = require("./store.controller");
const router = (0, express_1.Router)();
router.get('/', store_controller_1.storeController.getAllStores);
router.get('/popular', store_controller_1.storeController.getPopularStores);
router.get('/recommendations', store_controller_1.storeController.getStoreRecommendations);
router.get('/search', store_controller_1.storeController.searchStores);
router.get('/category/:kategori', store_controller_1.storeController.getStoresByCategory);
router.get('/:id/products', store_controller_1.storeController.getStoreProducts);
router.get('/:id', store_controller_1.storeController.getStoreById);
exports.default = router;
