"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const buyer_controller_1 = require("./buyer.controller");
const router = (0, express_1.Router)();
router.get('/', buyer_controller_1.buyerProductController.getAllProducts);
router.get('/popular', buyer_controller_1.buyerProductController.getPopularProducts);
router.get('/recommendations', buyer_controller_1.buyerProductController.getProductRecommendations);
router.get('/search', buyer_controller_1.buyerProductController.searchProducts);
router.get('/category/:kategori', buyer_controller_1.buyerProductController.getProductsByCategory);
router.get('/:id', buyer_controller_1.buyerProductController.getProductById);
exports.default = router;
